analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.7598566
  lightness: 0
  brandStrength: 0.4767025
  brandColors:
    - '#030303'
    - '#393939'
    - '#777777'
    - '#FFFFFF'
    - '#E0E0E0'
  rhythmicContrast: 0.7634408
typography_spectrum: 0.7329749
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.03405018
favicon: null
name: larsnordin
