name: larsnordin
favicon: null
layout_spectrum: 0.4839
typography_spectrum: 0.6702509
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F3FFFF'
    - '#161515'
    - '#425C6E'
    - '#BDA388'
    - '#F20C0C'
  brandStrength: 0.4749104
  lightness: 0
  saturation: 0.7598566
  rhythmicContrast: 0.7634408
purpose: []
